- buildAndReleaseTask/task.json
This PR should enhance the UX a bit by making the command `string` a `pickList` of all allowed commands for the pulumi binary.
Good idea?
> Make command picklist of allowed commands

- buildAndReleaseTask/index.ts
- buildAndReleaseTask/installers/pulumi.ts
- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/package.json
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/task.json
- buildAndReleaseTask/vars.ts
- Set PULUMI_CONFIG_PASSPHRASE in the exec options.
- Set the installed pulumi version so that subsequent instances of the same task can just reuse the version of the CLI that was installed by a preceding instance of the task.
> Set PULUMI_CONFIG_PASSPHRASE in the exec options

- azure-pipelines.yml
- buildAndReleaseTask/index.ts
- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/serviceEndpoint.ts
- buildAndReleaseTask/task.json
- buildAndReleaseTask/tests/_suite.ts
- buildAndReleaseTask/tests/envvars.ts
- buildAndReleaseTask/tests/package-lock.json
- buildAndReleaseTask/tests/package.json
- buildAndReleaseTask/tests/success.ts
- examples/azure-pipelines.yml
- vss-extension.json
Fixes #21.
We used to require the Azure Service Connection -- a way to provide credentials to Azure securely, which prohibits users from running Pulumi apps that target other cloud providers. This PR adds the ability to specify AWS credentials via env vars and makes the Azure Service Connection optional.
> Make Azure Service Connection Optional

- buildAndReleaseTask/pulumi.ts
Fixes #23.
On build agents, the `HOME` env var is not set and this causes the [dotnet CLI to fail](https://github.com/dotnet/cli/issues/8053). Use the built-in fallback `Agent.TempDirectory` if `DOTNET_CLI_HOME` itself is not defined and if all else fails, let the Pulumi CLI fail too, so that the user can set an appropriate home path for the dotnet CLI.
> Allow DOTNET_CLI_HOME to be set for the Pulumi CLI

- buildAndReleaseTask/index.ts
- buildAndReleaseTask/installers/pulumi.ts
- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/package.json
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/task.json
- buildAndReleaseTask/tests/package-lock.json
- buildAndReleaseTask/tests/package.json
- buildAndReleaseTask/vars.ts
- overview.md
Resolves #24.
In a previous PR I added support for setting the `AWS_*` env vars. But I had done that by manually mapping the build agent variables to the Pulumi CLI's execution environment. With this PR, I am changing that to use `getVariables` which would return all build variables, and I simply pass that onto to the Pulumi CLI's execution environment as-is. This allows users to set the env vars as described on Pulumi's docs.
> Use getVariables instead of individually mapping env vars

- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/task.json
This PR adds a new (optional) task extension param, that allows a user to pass args to the `login` command. This is useful for specifying args that are only applicable to the `login` command.
> Add a new task param for specifying login args.

- buildAndReleaseTask/pulumi.ts
This PR adds the `process.env` map to the tool runner's exec options, so that all built-in system and agent variables are available to the Pulumi CLI as an env var in the format that it expects (i.e., upper-cased, spaces and dots replaces with `_`.)
> Assign full Node process.env map to the exec options for the tool runner

- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/task.json
We check if the user has supplied at least one form of logging in to the Pulumi CLI, and that check wasn't accounting for the newly-added `loginArgs` task input variable. This PR fixes that.
> Check if loginArgs are passed before failing the task

- .github/pull_request_template.md
- README.md
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/task.json
- buildAndReleaseTask/tests/_suite.ts
- buildAndReleaseTask/tests/create_stack_if_not_found.ts
- buildAndReleaseTask/tests/envvars.ts
- buildAndReleaseTask/tests/success.ts
Fixes #33. Resolves #34.
* Removed the `init` command from the pick list for the `command` input.
* Added a new group (Advanced Options; see screenshot below) to put options that are slightly beyond the average use.
* Added the `createStack` boolean task input to the advanced options group, so that a user can indicate they would like to create the stack if it does not exist already.
This is how it looks in the Azure Pipelines build configuration UI:
> Allow users to indicate if a stack should be created, if it does not exist

- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/package.json
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/tests/_suite.ts
- buildAndReleaseTask/tests/package-lock.json
- buildAndReleaseTask/tests/package.json
I believe this should fix the issues #44, #48 and potentially #50 as well. The 3 issues are related to this task executing the `pulumi login` command in a shell without the `process.env` vars mapped to the executing shell. This prevented users from being able to use an Azure Storage backend when they would set additional env vars such as the `AZURE_STORAGE_ACCOUNT` and the `AZURE_STORAGE_KEY` env vars in the Pulumi step.
The other issue was that when using an Azure Service Connection, this task was only setting the `ARM_*` env vars, but not `AZURE_*` as required by the Azure SDK for Go, which is used by Pulumi for supporting Azure KeyVault as a secrets provider.
> Fix for using Azure Storage backend with env vars and Azure KeyVault secrets provider

- azure-pipelines.yml
- buildAndReleaseTask/pulumi.ts
- package.azure-pipelines.yml
It appears that the version that we were using has become quite old. An issue with one of the dependencies of tfx-cli is causing an error message to be written to STDERR that fails the build. This was [fixed](https://github.com/microsoft/azure-devops-extension-tasks/pull/177) in the 3.x version of the suite of extensions that we use for querying, packaging and publishing our extension to the VS Marketplace. So this PR updates the versions that we use to the newer ones.
> Update the versions for the DevOps Extensions management extensions

- package.azure-pipelines.yml
For whatever reason, the new version of the `PackageAzureDevOpsExtension` that we use to create a VSIX bundle doesn't work if we use the default variable names, i.e. `Extension.Version` that the previous step `QueryAzureDevOpsExtensionVersion` sets. Weirdly enough, The `QueryAzureDevOpsExtensionVersion` step does actually set the right value. I haven't dug into what's going on, but using a different variable name does work as expected. We do something [similar](https://github.com/pulumi/pulumi-az-pipelines-task/blob/master/azure-pipelines.yml#L92) in the primary build, which is what led me to suspect that if it works there it must work here too. Anyway, I triggered a manual build for the packaging build pipeline using this branch and it passed.
> Change the output variable name for the packaging build

- azure-pipelines.yml
- buildAndReleaseTask/index.ts
- buildAndReleaseTask/installers/pulumi.ts
- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/package.json
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/task.json
- buildAndReleaseTask/tests/create_stack_if_not_found.ts
- buildAndReleaseTask/tests/envvars.ts
- buildAndReleaseTask/tests/envvars_storage.ts
- buildAndReleaseTask/tests/package-lock.json
- buildAndReleaseTask/tests/package.json
- buildAndReleaseTask/tests/success.ts
- integrationtest.azure-pipelines.yml
- package.azure-pipelines.yml
- Add the extracted tool path to the tool cache dir. (fixes #59)
- Create the stack using the -c flag if the CLI version is newer than 1.10.0. (closes #38, closes #53)
- Make the `pulumi` command optional so that users can use the task to simply install the CLI.
> Various fixes

- buildAndReleaseTask/installers/pulumi.ts
Fixes #64 
Sets the correct folder to prepend to path and cache in the tool path as the Pulumi binary exists in a `pulumi` sub-folder in the extracted tar.gz, similar to Windows
Thank you for contributing! Before submitting your PR, can you please confirm that you have done the following?
> Update cache directory and PATH to use the correct folder

- buildAndReleaseTask/pulumi.ts
- overview.md
Remove unnecessary defaulting of DOTNET_CLI_HOME variable to allow OS to determine this behaviour.
Related to #40
Thank you for contributing! Before submitting your PR, can you please confirm that you have done the following?
> Remove setting DOTNET_CLI_HOME variable

- integrationtest.azure-pipelines.yml
Unfortunately the previous PR failed after merging due to the integration test pipeline config containing an invalid job name.
> Fix job name to not have dashes

- integrationtest.azure-pipelines.yml
This one was a surprise to me. That the CLI needs to login in order to set a plaintext stack config. If I was setting a secret, I can understand the need for the access token due to the stack using service-managed secrets. Anyway, is that intended behavior of the CLI? To fix this I have now explicitly mapped the access token for the `script` step since it is a secret. Secret vars need to be explicitly mapped to `script` steps.
> script tasks need to get env vars explicitly mapped

- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/package.json
- buildAndReleaseTask/task.json
Fixes #84.
The task thankfully does not depend on anything specific to legacy Node versions. To provide some background, when the task was authored it's just that the tutorials for creating a custom task extension used the execution target as `Node` instead of `Node10`. I am not even sure if Azure Pipelines had support for Node10+ execution targets back when this was originally authored.
I followed the guide from https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md.
> Migrate task to Node10 runtime

- azure-pipelines.yml
The stage that builds/publishes a test version of the task extension for integration test purposes is being skipped because Az Pipelines service is failing to find an agent with the following error:
```
##[warning]An image label with the label Ubuntu16 does not exist.
,##[error]The remote provider was unable to process the request.
Pool: Azure Pipelines
Image: Ubuntu16
```
It looks like the agent pool image is defaulting to an old version of ubuntu that perhaps no longer is in service in Az Pipelines? In any case, this PR sets the pool image for the relevant stage similar to the other ones in the pipelines.
> Set the job pool explicitly for the test packaging stage

- .prettierignore
- azure-pipelines.yml
- buildAndReleaseTask/installers/pulumi.ts
- buildAndReleaseTask/models.d.ts
- buildAndReleaseTask/package.json
- buildAndReleaseTask/prComment.ts
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/serviceEndpoint.ts
- buildAndReleaseTask/taskConfig.ts
- buildAndReleaseTask/tests/_suite.ts
- buildAndReleaseTask/tests/create_stack_if_not_found.ts
- buildAndReleaseTask/tests/envvars.ts
- buildAndReleaseTask/tests/envvars_storage.ts
- buildAndReleaseTask/tests/success.ts
- buildAndReleaseTask/version.ts
- package.azure-pipelines.yml
- package.json
@RobbieMcKinstry as discussed, this PR with various miscellaneous fixes. The highlight of the PR is to run lint as part of CI/PR builds. Most of the changes come from the first commit in this PR, which is related to re-enabling code formatting with Prettier.
I also decided to pull out the `TaskConfig` interface into a type definition file after all, given how much trouble it led to in my previous PR with the incorrect import. It should help avoid similar problems for others in the future.
-------
> Run lint as part of CI

- buildAndReleaseTask/prComment.ts
- buildAndReleaseTask/task.json
- buildAndReleaseTask/tests/_suite.ts
- overview.md
This PR should fix #118. The default value for the PR comment input should be `false` and the default value for using threaded comments should be `true`. These were flipped unfortunately when the feature was added, which caused release pipelines to fail since the task was throwing an error about the lack of a PR ID.
--------
> PR comment feature should be opt-in and not enabled by default

- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/serviceEndpoint.ts
Thank you for contributing! Before submitting your PR, can you please confirm that you have done the following?
* 
fixes: [#122](https://github.com/pulumi/pulumi-az-pipelines-task/issues/122)
> Make subscriptionId an optional parameter when looking up the endpoint service metadata

- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/task.json
- package-lock.json
- package.json
Release pipelines in Azure DevOps are UI-based unlike build pipelines which are primarily configured using YAML and allows for env vars to be passed using the YAML key `env:` for all tasks. This task extension can be used in both build and release pipelines. Setting [`showEnvironmentVariables`](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json#L49) to `true` will now show an Environment Variables configuration panel only in the Releases view. In the regular build pipeline, no new panel is added (can provide a screenshot of that too if needed.)
For additional context, see: https://pulumi-community.slack.com/archives/CRVK66N5U/p1700433168859369
I installed a private version of the extension with these changes into my own DevOps organization and can confirm …
> Set showEnvironmentVariables to true for the pipeline task

- azure-pipelines.yml
- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/package.json
- buildAndReleaseTask/task.json
- buildAndReleaseTask/tests/package-lock.json
- buildAndReleaseTask/tests/package.json
- package.azure-pipelines.yml
This PR updates many dependencies to their latest version in order to support the Node16 execution handler. Most notable upgrades are [`azure-pipelines-task-lib`](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/CHANGELOG.md#4x) and [`azure-pipelines-tool-lib`](https://github.com/microsoft/azure-pipelines-tool-lib/blob/master/CHANGELOG.md#2x) which are crucial SDKs for custom task extensions. I had a look at the changelog for those two packages and didn't see anything concerning.
The `Node10` execution handler must remain in the extension manifest until Azure stops supporting older build agents completely. They released v3.x for build agents earlier this year. While Microsoft-hosted build agents will automatically use the latest agent version, self-hosted build …
> Support Node16 execution handler for newer build agents

- buildAndReleaseTask/package-lock.json
- buildAndReleaseTask/package.json
- buildAndReleaseTask/pulumi.ts
- buildAndReleaseTask/serviceEndpoint.ts
Add support for [Workload identity federation for Azure service connections](https://devblogs.microsoft.com/devops/workload-identity-federation-for-azure-deployments-is-now-generally-available/).
This change is based on the implementation in the [Azure CLI Task V2](https://github.com/microsoft/azure-pipelines-tasks/blob/5278dc64cd07ce067e40f3e4a2bf5e15edf12b57/Tasks/AzureCLIV2/azureclitask.ts).
Added [azure-pipelines-tasks-artifacts-common@2.230.0](https://www.npmjs.com/package/azure-pipelines-tasks-artifacts-common/v/2.230.0) so the [getSystemAccessToken](https://github.com/microsoft/azure-pipelines-tasks/blob/68caa90dd430a9f2a1cb2cacc1d8b6fcc48fbb71/Tasks/GradleV3/Modules/environment.ts#L10-L27) function could be used to get the system token to auth the request for the creation of the …
> Support workload identity federation service connection (#147)

- buildAndReleaseTask/prComment.ts
Fixes https://github.com/pulumi/pulumi-az-pipelines-task/issues/134.
When searching for comments from the pulumi tool filter out threads without "source" set.
> Filter comments without source set

- examples/azure-native-dotnet/azure-dotnet.csproj
This change upgrades Azure Native in the example to the latest version, which has [better oidc support](https://github.com/pulumi/pulumi-azure-native/issues/2884), which is needed to run the integration tests that now use oidc for authentication with Azure.
> chore: Use the latest Azure Native in example

- examples/azure-native-dotnet/azure-dotnet.csproj
The test pipeline on merge to master is currently failing with
```
pulumi:pulumi:Stack (pulumi-az-pipelines-task-azure-dotnet-dev):
You must install or update .NET to run this application.
App: /home/vsts/work/1/s/examples/azure-native-dotnet/bin/Debug/net6.0/azure-dotnet
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet
The following frameworks were found:
8.0.16 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
```
https://dev.azure.com/pulumi/Pulumi%20Azure%20Pipelines%20Task/_build/results?buildId=534&view=logs&j=86c4f51f-3948-5d48-5a77-40c0b241e1ef&t=e43b5afd-f7c1-5544-3510-8415c558bba4
> Update dotnet example to use 8.0
